# Generated by Django 5.0.1 on 2024-03-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
