# Generated by Django 5.0.1 on 2024-03-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_contact_number_student_facebook_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('student', 'student'), ('teacher', 'teacher'), ('cr', 'cr')], default='admin', max_length=20),
        ),
    ]
