# Generated by Django 5.0.1 on 2024-03-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_student_gender_alter_teacher_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Profile_Pictures'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Profile_Pictures'),
        ),
    ]
