# Generated by Django 5.0.1 on 2024-03-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_student_gender_alter_student_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
