# Generated by Django 5.0.1 on 2024-02-16 12:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonBaseModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingExams',
            fields=[
                ('commonbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonbasemodel')),
                ('exam_name', models.CharField(choices=[('Class Test', 'Class Test'), ('Quiz Test', 'Quiz Test'), ('Mid Term', 'Mid Term'), ('Final Test', 'Final Test')], max_length=10)),
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=7)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=150)),
                ('detail', models.TextField()),
            ],
            bases=('common.commonbasemodel',),
        ),
    ]
