# Generated by Django 5.0.1 on 2024-02-16 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingexams',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.departments'),
        ),
        migrations.AddField(
            model_name='upcomingexams',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.intakes'),
        ),
        migrations.AddField(
            model_name='upcomingexams',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sections'),
        ),
    ]
