# Generated by Django 5.0.1 on 2024-03-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_classroutine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='building',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='room',
            field=models.PositiveIntegerField(),
        ),
    ]
