# Generated by Django 5.0.1 on 2024-03-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_classroutine_building_alter_classroutine_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='course_code',
            field=models.CharField(max_length=8),
        ),
    ]
