# Generated by Django 5.0.1 on 2024-03-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_classroutine_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('commonbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonbasemodel')),
                ('course_code', models.CharField(max_length=8)),
                ('course_title', models.CharField(max_length=100)),
                ('assignment_title', models.CharField(max_length=150)),
                ('detail', models.TextField()),
            ],
            bases=('common.commonbasemodel',),
        ),
    ]
