# Generated by Django 5.0.1 on 2024-03-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_assignments'),
        ('users', '0007_alter_student_account_alter_teacher_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.departments'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.intakes'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sections'),
        ),
    ]
