# Generated by Django 5.0.1 on 2024-03-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_assignments_department_assignments_intake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='types',
            field=models.CharField(choices=[('assignment', 'assignment'), ('lab_report', 'Lab Report'), ('presentation', 'Peresentation')], default='assignment', max_length=50),
        ),
    ]
